version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  api:
    build: .
    container_name: deepseek-api
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - MODEL_NAME=deepseek-coder
    ports:
      - "8080:8080"
    depends_on:
      - ollama

volumes:
  ollama_data:

networks:
  ai-network:
    driver: bridge 