version: '3.8'

services:
  api:
    build: .
    container_name: deepseek-api
    ports:
      - "8080:8080"
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_API_URL=http://localhost:11434
      - OLLAMA_MODEL=deepseek-coder
      - OLLAMA_TIMEOUT_SECONDS=120

volumes:
  ollama_data:

networks:
  ai-network:
    driver: bridge 