openapi: 3.0.0
info:
  title: DeepSeek Coder API
  version: 1.0.0
  description: |
    API for generating code using DeepSeek Coder model through Ollama.
    
    This API provides endpoints for:
    - Generating code based on natural language prompts
    - Checking the health and status of the service
servers:
  - url: https://{baseUrl}/ollama/choreo/v1.0
    variables:
      baseUrl:
        default: localhost:8080
        description: Base URL of the API
paths:
  /health:
    get:
      summary: Health Check
      description: Check the health status of the API and Ollama service
      operationId: healthCheck
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /generate:
    post:
      summary: Generate Code
      description: Generate code using DeepSeek Coder model
      operationId: generateCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequest'
      responses:
        '200':
          description: Successfully generated code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Failed to connect to Ollama
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '504':
          description: Request timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    GenerateRequest:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: The natural language prompt for code generation
          example: "Write a Python function to calculate fibonacci sequence"
    GenerateResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success]
          description: Status of the request
        model:
          type: string
          description: The model used for generation
        generated_code:
          type: string
          description: The generated code
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          description: Overall health status
        service:
          type: string
          description: Service name
        ollama:
          type: object
          properties:
            url:
              type: string
              description: Ollama service URL
            status:
              type: string
              enum: [connected, disconnected, error, timeout]
              description: Ollama connection status
            model:
              type: string
              description: Current model name
            error:
              type: string
              description: Error message if any
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message 